/** Industry-aligned default plans (POS SaaS ~$49–$129/mo tier). Upserted when catalog is empty. */
export const DEFAULT_SUBSCRIPTION_PLANS = [
  {
    name: 'Basic',
    price: 49,
    period: 'monthly',
    sortOrder: 1,
    isActive: true,
    userLimit: 5,
    storeLimit: 1,
    storageLimitMB: 500,
    description:
      'Essential cloud POS for single-store retailers — checkout, inventory, and daily reports.',
    features: [
      'Cloud POS & barcode checkout',
      'Products, inventory & stock alerts',
      'Sales history & customer profiles',
      'Basic sales & tax reports',
      'Email support · 1 store · 5 users',
      '500 MB document storage',
    ],
  },
  {
    name: 'Pro',
    price: 99,
    period: 'monthly',
    sortOrder: 2,
    isActive: true,
    userLimit: 15,
    storeLimit: 5,
    storageLimitMB: 2000,
    description:
      'For growing teams — multi-store ops, purchases, suppliers, HRM, and advanced analytics.',
    features: [
      'Everything in Basic',
      'Purchases, GRN & supplier management',
      'HRM: attendance, leave & payroll exports',
      'Multi-store dashboard & transfers',
      '14+ reports with CSV/Excel export',
      'Priority email & chat support · 5 stores · 15 users',
      '2 GB storage',
    ],
  },
  {
    name: 'Enterprise',
    price: 0,
    period: 'monthly',
    sortOrder: 3,
    isActive: true,
    userLimit: 999,
    storeLimit: 999,
    storageLimitMB: 50000,
    description: 'Unlimited scale with finance, API access, custom SLAs, and dedicated onboarding.',
    features: [
      'All modules including Finance & API',
      'Unlimited stores & users (fair use)',
      'Custom roles, SSO-ready architecture',
      'Dedicated account manager',
      '99.9% uptime SLA & migration support',
      'Custom integrations & volume pricing',
      '50 GB+ storage',
    ],
  },
];
